query($searchQuery: String) {
  searchImages(searchQuery: $searchQuery) {
    id
    name
    slug
    description
    location
    date_taken
    price

    src {
      url
      formats
    }

    gallery {
      slug
    }
  }
}
