query($searchQuery: String) {
  images(
    where: {
      tags: { title_contains: $searchQuery }
      name_contains: $searchQuery
    }
  ) {
    id
    name
    slug
    src {
      url
      formats
    }
  }
}
