query Galleries {
  galleries {
    id
    title
    slug

    source {
      id
      public_id
      title
    }

    images(sort: "created_at:desc") {
      id
      date_taken
      description
      location
      title
      price
      size_description
      slug

      sources {
        id
        public_id
        title
      }

      gallery {
        slug
      }
    }
  }
}
