query Gallery($slug: String!) {
  gallery: galleryBySlug(slug: $slug) {
    id
    name
    slug

    source {
      id
      public_id
      title
    }

    images {
      id
      date_taken
      description
      location
      name
      price
      size_description
      slug
    }
  }
}
