query Galleries {
  galleries {
    id
    name
    slug

    source {
      id
      title
      public_id
    }

    images {
      id
      name
      slug
      description
      location
      date_taken
      price

      sources {
        id
        title
        public_id
      }

      gallery {
        slug
      }
    }
  }
}
