query Image($slug: String!) {
  image: imageBySlug(slug: $slug) {
    id
    name
    slug
    description
    location
    price
    date_taken

    src {
      url
      formats
    }

    gallery {
      slug
    }
  }
}
