query Gallery($start: Int, $limit: Int, $sort: String) {
  galleriesNextPagination: galleriesConnection(
    start: $start
    limit: $limit
    sort: $sort
  ) {
    values {
      id
      name
      slug
    }
    aggregate {
      count
      totalCount
    }
  }
  galleriesPrevPagination: galleriesConnection(
    start: $start
    limit: $limit
    sort: $sort
  ) {
    values {
      id
      name
      slug
    }
    aggregate {
      count
      totalCount
    }
  }
}
